name: Deploy folder to Pages

on:
  workflow_dispatch:
  push:
    branches: ["main"] # 當 main 分支有更新時觸發

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 這裡是最關鍵的一步：指定你要上傳的資料夾路徑
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
